### ISSUE TITLE
H5PY File Not Working for FMoW

### ISSUE THREAD

**Issue by Nyquixt** [wistuba/Wild-Time-Data#1] opened 2023-05-10 02:16 UTC
Hi,

When I downloaded FMoW, it cannot open the h5py file with the following error thrown:

```
Traceback (most recent call last):
  File "toy_exp.py", line 14, in <module>
    dataset = load_dataset(dataset_name='fmow', time_step=0, split='train', data_dir='./datasets/WildTimeDatasets/')
  File "venv/lib/python3.8/site-packages/wild_time_data/core.py", line 79, in load_dataset
    return dataset_classes[dataset_name](
  File "venv/lib/python3.8/site-packages/wild_time_data/datasets.py", line 41, in __init__
    self._file = h5py.File(os.path.join(data_dir, self.file_name), "r")
  File "venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

Could you double check? Thanks!

-K

**Comment by wistuba** [comment] 2023-05-10 08:59
Thanks a lot for reporting the problem. I've quickly checked but cannot reproduce your problem so far. I will spend some more time to dig a bit deeper. Hopefully I can fix this quickly. I will keep you posted.

**Comment by wistuba** [comment] 2023-05-10 15:11
Sorry, I cannot reproduce your error.

I've create a new Python environment

```
conda create -n my_env python=3.9
```
activated it
```
conda activate my_env
```
and installed `wild-time-data`
```
pip install wild-time-data
```
Next, I've prepared the dataset as follows:
```
git clone https://github.com/wistuba/Wild-Time-Data.git
cd Wild-Time-Data/converter
pip install -r requirements.txt
python fmow.py --data-dir .
```
Two hours later, the HDF5 file was created and I ran in the same location
```
load_dataset(dataset_name="fmow", split="train", time_step=0, data_dir=".")
```

Did you follow the same procedure? If you share a bit more about your settings and process, I might be able to reproduce your problem.

**Comment by wistuba** [comment] 2023-05-10 15:14
Maybe your file got corrupted while creating it? Please check [this stackoverflow post](https://stackoverflow.com/questions/38089950/error-opening-file-in-h5py-file-signature-not-found) and how to figure it out. You might want to consider recreating the HDF5 file.

**Comment by wistuba** [comment] 2023-06-02 10:46
Does this problem still exist? Otherwise I will close this issue.

**Closed as completed** 2023-06-18 15:38 UTC
